.TH NAUTILUS-COMPARE-PREFERENCES 1 "December 20, 2024"
.SH NAME
nautilus-compare-preferences \- Preferences dialog for Nautilus Compare extension
.SH SYNOPSIS
.B nautilus-compare-preferences
.SH DESCRIPTION
A graphical preferences dialog for the \fINautilus Compare\fP
simplifies choosing diff applications started via the context menu
of the \fINautilus file manager\fP.
.PP
Using the preferences dialog you can select and switch between comparison
tools to perform diffs, three-way diffs and multi-diffs. Known diff tools
are detected from common install locations at \fI/usr/[local/]bin\fP
and the preferences dialog is pre-filled with potential names for comparators.
.PP
To apply the changes, a restart of the Nautilus file manager is required.
Run the command \fI"nautilus -q"\fP to quit Nautilus and restart it to reflect
the updated settings.
.PP
The extension and the preferences dialog were written in Python and GTK+.
.SH FILES
.I /etc/nautilus-compare.conf
.RS
System wide preferences file.
.RE
.I $XDG_CONFIG_HOME/nautilus-compare.conf
.RS
Local preferences file.
.RE
.SH SEE ALSO
.BR nautilus (1)
.br
.SH AUTHOR
.nh
Written by
.MT tramm@\:infoaed.ee
Märt Põder
.ME
.UE ,
inspired by the discontiued
.I diff-ext
extension in 2011.